project:
  title: node-echo
  version: 0.1.9
  copyright: Digital Butter Limited
  project_url: http://digitalbutter.github.com/node-echo/
  source_url: https://github.com/digitalbutter/node-echo/
  git_url: git@github.com:digitalbutter/node-echo.git
  api_url: http://digitalbutter.github.com/node-echo/api/index.html
  author:
      name: Ed Bosher
      gh_account: https://github.com/edbo
  contributors:
    - name: Emmanuel Prochasson
      gh_account: https://github.com/eprochasson
npm:
  version: 0.1.9
  name: echo
page:
  title: digitalbutter/node-echo @ Github
  github_account: digitalbutter
  output_dir: tmp/output/
  repo_name: digtalbutter/node-echo
  content: README.markdown
  google_analytics_code: UA-16228137-11
page_publish:
  source_dir: tmp/output
doc:
  output_dir: tmp/output/api
  parser_out_dir: tmp/parser
  source_dir: lib/
  template_dir: ~/buildTools/yuidoc-dana/